apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- application
- argo
- pipeline
- metadata
- cache
- cache-deployer

resources:
  - namespace.yaml
  - pipeline-application.yaml  

# Used by Kustomize
configMapGenerator:
  - name: pipeline-parameters
    env: params.env

vars:
  - name: NAMESPACE
    objref:
      kind: Deployment
      apiVersion: apps/v1
      name:  workflow-controller
    fieldref:
      fieldpath: metadata.namespace
  - name: APP_NAME
    objref:
      kind: ConfigMap      
      name:  pipeline-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.appName
  - name: APP_VERSION
    objref:
      kind: ConfigMap      
      name:  pipeline-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.appVersion
  - name: IMAGE_TAG
    objref:
      kind: ConfigMap      
      name:  pipeline-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.imageTag

configurations:
  - params.yaml
