apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../dev
  - proxy

# Identifier for application manager to apply ownerReference.
# The ownerReference ensures the resources get garbage collected
# when application is deleted.
commonLabels:
  application-crd-id: kubeflow-pipelines

# Replace with your namespace
namespace: kubeflow

images:
  - name: mysql
    newTag: "5.6"
  - name: minio/minio
    newTag: RELEASE.2018-02-09T22-40-05Z
  - name: gcr.io/ml-pipeline/inverse-proxy-agent
    newTag: "0.4.0"
