apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../env/gcp

# Used by Kustomize
configMapGenerator:
  - name: pipeline-parameters
    env: params.env
    behavior: merge

#### Customization ###
# 1. Replace with your namespace
namespace: myKubeflow
# 2. Change values in params.env file
