apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ml-pipeline
  name: ml-pipeline
spec:
  selector:
    matchLabels:
      app: ml-pipeline
  template:
    metadata:
      labels:
        app: ml-pipeline
    spec:
      containers:
      - env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        # - name: MINIO_SERVICE_SERVICE_HOST
        #   value: "minio-service.$(NAMESPACE)"
        # - name: MINIO_SERVICE_SERVICE_PORT
        #   value: "9000"
        - name: OBJECTSTORECONFIG_SECURE
          value: "false"
        image: gcr.io/ml-pipeline/api-server:$(IMAGE_TAG)
        imagePullPolicy: IfNotPresent
        name: ml-pipeline-api-server
        ports:
        - containerPort: 8888
        - containerPort: 8887
      serviceAccountName: ml-pipeline
