apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../namespaced
  - ../gcp-dev/proxy
  - gcsgateway
  - cloudsqlproxy

# Identifier for application manager to apply ownerReference.
# The ownerReference ensures the resources get garbage collected
# when application is deleted.
commonLabels:
  application-crd-id: kubeflow-pipelines

# Replace with your namespace
namespace: kubeflow

patchesStrategicMerge:
  - gcp-configurations-patch.yaml

images:
  - name: gcr.io/cloudsql-docker/gce-proxy
    newTag: "1.14"
  - name: gcr.io/ml-pipeline/minio
    newTag: RELEASE.2019-08-14T20-37-41Z-license-compliance
